snapx-team/laravel-kanban

src/Commands/MoveErpDataInTaskToErpShareables.php
src/LaravelKanbanServiceProvider.php
src/Models/ErpShareables.php

Create a command that'll move the contracts and the erp employees from tasks table to the shareables table.

[XGUARD-1340] migrate erp data to shareables

---

package-lock.json
package.json
src/resources/js/app.js
src/resources/js/components/dashboard/dashboardComponents/Actions.vue
src/resources/js/components/dashboard/dashboardComponents/AddOrEditEmployeeModal.vue
src/resources/js/components/global/Avatar.vue
src/resources/js/components/global/SideBar.vue
src/resources/js/components/kanban/Kanban.vue

Added collapsilble nav bar with a collapsible button to link to other kanban versions (ontario, signaleurs, scheduler)
Also handled touch devices by disabling instant drag on ios, android, and other mobile devices.  Instead, a hold then drag feature was implemented on those devices

[XGUARD-1316][XGUARD-1317]

---

package-lock.json
package.json
src/Actions/Tasks/UpdateTaskStatusAction.php
src/Http/Controllers/LaravelKanbanController.php
src/Http/Controllers/MetricsController.php
src/Models/Log.php
src/resources/js/app.js
src/resources/js/components/backlog/Backlog.vue
src/resources/js/components/backlog/backlogComponents/BacklogCard.vue
src/resources/js/components/backlog/backlogComponents/BoardPaneCard.vue
src/resources/js/components/kanban/kanbanComponents/taskComponents/ViewTaskData.vue

when you right click on a backlog item, you can change status

[ XGUARD-525] context menu -> status change in backlog

---

src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/dashboard/dashboardComponents/AddBacklogTaskModal.vue
src/resources/js/components/kanban/kanbanComponents/AddTaskByColumnModal.vue
src/resources/js/components/kanban/kanbanComponents/taskComponents/ViewTaskData.vue

Every modal where we can search for a task to group by was broken other than the one in task pane.

[XGUARD-2765] Fix searchable tasks in modals

---

src/Actions/Tasks/UpdateTaskDescriptionAction.php
src/Models/Log.php
src/resources/js/components/kanban/kanbanComponents/taskComponents/TaskComments.vue

[XGUARD-2863] fix task status change notification
[XGUARD-2862] error message with checkbox
[XGUARD-2846] fix comment error message
[XGUARD-2863]: https://snapx-team.atlassian.net/browse/XGUARD-2863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-2862]: https://snapx-team.atlassian.net/browse/XGUARD-2862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-2846]: https://snapx-team.atlassian.net/browse/XGUARD-2846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[XGUARD-2863] [XGUARD-2862] [XGUARD-2846]

---

src/Actions/Metrics/GetAverageTimeToCompletionByBadgeAction.php
src/Actions/Metrics/GetAverageTimeToCompletionByEmployeeAction.php
src/Actions/Metrics/GetBadgeDataAction.php
src/Actions/Metrics/GetClosedTasksByAdminAction.php
src/Actions/Metrics/GetClosedTasksByAssignedToAction.php
src/Actions/Metrics/GetContractDataAction.php
src/Actions/Metrics/GetCreatedVsResolvedAction.php
src/Actions/Metrics/GetEstimatedHoursCompletedByEmployeesAction.php
src/Actions/Metrics/GetPeakHoursTasksCreatedAction.php
src/Actions/Metrics/GetTasksCreatedByEmployeeAction.php
src/Http/Controllers/MetricsController.php
src/Models/Log.php
src/database/factories/KanbanErpSharebalesFactory.php
src/database/factories/KanbanLogFactory.php
src/resources/js/components/metrics/Metrics.vue
src/resources/js/components/metrics/metricsComponents/BarChart.vue
src/resources/js/components/metrics/metricsComponents/LineChart.vue
src/resources/js/mixins/ajaxCallsMixin.js
tests/Unit/Actions/Metrics/GetAverageTimeToCompletionByBadgeActionTest.php
tests/Unit/Actions/Metrics/GetAverageTimeToCompletionByEmployeeActionTest.php
tests/Unit/Actions/Metrics/GetBadgeDataActionTest.php
tests/Unit/Actions/Metrics/GetClosedTasksByAdminActionTest.php
tests/Unit/Actions/Metrics/GetClosedTasksByAssignedToActionTest.php
tests/Unit/Actions/Metrics/GetContractDataActionTest.php
tests/Unit/Actions/Metrics/GetCreatedVsResolvedActionTest.php
tests/Unit/Actions/Metrics/GetEstimatedHoursCompletedByEmployeesActionTest.php
tests/Unit/Actions/Metrics/GetPeakHoursTasksCreatedActionTest.php
tests/Unit/Actions/Metrics/GetTasksCreatedByEmployeeActionTest.php

moved a bunch of controller functions to actions and created subsequent tests
-  x] Associated with a JIRA issue.

[XGUARD-2901] metrics actions refactor

---

src/resources/views/index.blade.php

bug fix to handle forced https by aws 

[XGUARD-3287] fix force https

---

src/Actions/Members/CreateMembersAction.php
src/Actions/Members/DeleteMemberAction.php
src/Entities/ErpContract.php
src/Entities/ErpUser.php
src/Http/Controllers/ErpController.php
src/Http/Controllers/MemberController.php
src/Models/Employee.php
src/Repositories/ErpContractsRepository.php
src/Repositories/ErpUsersRepository.php
src/Repositories/MembersRepository.php
src/resources/js/components/backlog/Backlog.vue
src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/dashboard/dashboardComponents/AddBacklogTaskModal.vue
src/resources/js/components/dashboard/dashboardComponents/AddOrEditEmployeeModal.vue
src/resources/js/components/kanban/kanbanComponents/AddTaskByColumnModal.vue
src/resources/js/components/kanban/kanbanComponents/taskComponents/AddTaskData.vue
tests/Unit/Actions/Members/CreateMembersActionTest.php
tests/Unit/Actions/Members/DeleteMemberActionTest.php
tests/Unit/Repositories/ErpContractsRepositoryTest.php
tests/Unit/Repositories/ErpUsersRepositoryTest.php
tests/Unit/Repositories/MembersRepositoryTest.php

[XGUARD-2898][XGUARD-2900] ERP Controller refactor

---

src/Actions/Boards/CreateBoardAction.php
src/Actions/Boards/DeleteBoardAction.php
src/Actions/Boards/EditBoardAction.php
src/Http/Controllers/BoardsController.php
src/Repositories/BoardsRepository.php
src/resources/js/components/dashboard/Dashboard.vue
src/resources/js/mixins/ajaxCallsMixin.js
src/routes/web.php
tests/Unit/Actions/Boards/CreateBoardActionTest.php
tests/Unit/Actions/Boards/DeleteBoardActionTest.php
tests/Unit/Actions/Boards/EditBoardActionTest.php
tests/Unit/Repositories/BoardsRepositoryTest.php

Merge branch 'develop' of https://github.com/snapx-team/xguard-schedule into develop

general ui fixesa and removal of unused imports

---

src/Actions/Rows/CreateOrUpdateRowAndColumnsAction.php
src/Http/Controllers/BoardsController.php
src/Http/Controllers/RowAndColumnsController.php
src/Models/Column.php
src/resources/js/App.vue
src/resources/js/components/global/SideBar.vue
src/resources/js/components/notifications/Notifications.vue

added live notification in sidebar. Fixed row/column not updating live

live notif update - [XGUARD-3390]

---

src/Models/Task.php
src/Models/TaskVersion.php
src/resources/js/components/kanban/kanbanComponents/taskComponents/LogCard.vue
src/resources/js/mixins/logFormatterMixin.js
tests/Unit/Actions/KanbanData/GetKanbanDataActionTest.php
tests/Unit/Actions/Tasks/UpdateTaskCardIndexesActionTest.php

[XGUARD-3520]
[XGUARD-3527]
[XGUARD-3438]
[XGUARD-3478]
Fixing issue where task-simple name breaking because board is deleted
Fixing issue where logs don't show up because loggable is a deleted value
fixed row/column not not being created dynamically
[XGUARD-3520]: https://snapx-team.atlassian.net/browse/XGUARD-3520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3527]: https://snapx-team.atlassian.net/browse/XGUARD-3527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3438]: https://snapx-team.atlassian.net/browse/XGUARD-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix withTrashed issue & create row&column

---

.circleci/config.yml

[XGUARD-3160] CI test

---

readme.md
src/Actions/Metrics/GetAverageTimeToCompletionByBadgeAction.php
src/Actions/Metrics/GetAverageTimeToCompletionByEmployeeAction.php
src/Actions/Metrics/GetBadgeDataAction.php
src/Actions/Metrics/GetClosedTasksByAdminAction.php
src/Actions/Metrics/GetClosedTasksByAssignedToAction.php
src/Actions/Metrics/GetContractDataAction.php
src/Actions/Metrics/GetCreatedVsResolvedAction.php
src/Actions/Metrics/GetEstimatedHoursCompletedByEmployeesAction.php
src/Actions/Metrics/GetPeakHoursTasksCreatedAction.php
src/Actions/Metrics/GetTasksCreatedByEmployeeAction.php
src/Actions/Tasks/PaginateBackLogTasksAction.php
src/QueryBuilders/TasksQueryBuilder.php
src/database/factories/KanbanTemplateFactory.php
src/resources/js/components/dashboard/dashboardComponents/EmployeeList.vue
src/resources/js/components/kanban/Kanban.vue
src/resources/js/components/metrics/Metrics.vue
src/resources/js/components/metrics/metricsComponents/BarChart.vue
src/resources/js/components/metrics/metricsComponents/LineChart.vue
src/resources/js/components/metrics/metricsComponents/PieChart.vue
src/resources/js/mixins/ajaxCallsMixin.js
src/resources/js/router/index.js
tests/Unit/Actions/DashboardData/GetDashboardDataActionTest.php

[XGUARD-3434][XGUARD-3434][XGUARD-1524]
- Fixing issue where error messages don't appear with invalid date combinations in metrics page
- Fixing infinite load when user tries to access board they're not a member of
- Fixing issue where searching task by status is overridden if you search by text
[XGUARD-3434]: https://snapx-team.atlassian.net/browse/XGUARD-3434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3434]: https://snapx-team.atlassian.net/browse/XGUARD-3434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-1524]: https://snapx-team.atlassian.net/browse/XGUARD-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

fixing various bugs

---

src/Actions/BacklogData/GetBacklogDataAction.php
src/Actions/Badges/CreateBadgeAction.php
src/Actions/Badges/DeleteBadgeAction.php
src/Actions/Badges/EditBadgeAction.php
src/Actions/Badges/ListBadgesWithCountAction.php
src/Actions/Notifications/NotifyEmployeesAction.php
src/Enums/LoggableTypes.php
src/Enums/Roles.php
src/Enums/SessionVariables.php
src/Enums/TaskStatuses.php
src/Models/Badge.php
src/Models/Board.php
src/Models/Employee.php
src/Models/Member.php
src/Models/Task.php
src/Models/Template.php

refactoring constants

---

src/Actions/KanbanData/GetKanbanDataAction.php
src/Actions/Metrics/GetBadgeDataAction.php
src/Actions/Metrics/GetClosedTasksByAssignedToAction.php
src/Actions/Metrics/GetTasksCreatedByEmployeeAction.php
src/Actions/Tasks/PlaceTaskAction.php
src/Http/Controllers/LaravelKanbanController.php
src/Http/Controllers/TaskController.php
src/Models/Board.php
src/Models/Column.php
src/Models/Member.php
src/Models/Row.php
src/Models/SharedTaskData.php
src/Models/Task.php
src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/global/SideBar.vue
src/resources/js/components/global/taskComponents/AddTaskData.vue
src/resources/js/components/global/taskComponents/PlaceTask.vue
src/resources/js/components/global/taskComponents/RelatedTasks.vue
src/resources/js/components/global/taskComponents/ViewTaskData.vue
src/resources/js/components/kanban/kanbanComponents/KanbanTaskModal.vue
src/resources/js/components/metrics/Metrics.vue
src/resources/js/components/metrics/metricsComponents/PieChart.vue
src/resources/js/mixins/ajaxCallsMixin.js
src/resources/js/mixins/logFormatterMixin.js
src/routes/web.php
tests/Unit/Actions/Tasks/PlaceTaskActionTest.php

also completed bug [XGUARD-3702]
also completed bug [XGUARD-3435]
Added button that allows user to remove a card from row/column
fixed date issue in metrics where invalid date combinations causing unusual behavior
fixed status not dynamically updating in backlog
[XGUARD-3702]: https://snapx-team.atlassian.net/browse/XGUARD-3702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3435]: https://snapx-team.atlassian.net/browse/XGUARD-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[XGUARD-1323] return to backlog

---

src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/global/Avatar.vue
src/resources/js/components/global/taskComponents/AddTaskData.vue
src/resources/js/components/global/taskComponents/PlaceTask.vue
src/resources/js/components/global/taskComponents/ViewTaskData.vue
src/resources/js/components/metrics/metricsComponents/BarChart.vue
src/resources/js/components/metrics/metricsComponents/LineChart.vue
src/resources/js/components/metrics/metricsComponents/PieChart.vue
src/resources/js/mixins/ajaxCallsMixin.js

removed api call from external website foir avatar. Made my own.
also fixed [XGUARD-3732] 
also fixed metrics graph showing old data if invalid data entered
[XGUARD-3732]: https://snapx-team.atlassian.net/browse/XGUARD-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

avatar icon refactor [XGUARD-1236]

---

src/Actions/DashboardData/GetDashboardDataAction.php
src/Http/Controllers/LogController.php
src/Models/Board.php
src/Models/Comment.php
src/Models/Log.php
src/Models/Task.php
src/Repositories/LogsRepository.php
src/resources/js/components/global/taskComponents/TaskLogs.vue
src/resources/js/components/notifications/Notifications.vue
src/resources/js/mixins/ajaxCallsMixin.js

[XGUARD-3751]
added pagination to logs
[XGUARD-3751]: https://snapx-team.atlassian.net/browse/XGUARD-3751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added pagination to logs [XGUARD-3751]

---

src/Actions/Metrics/GetClosedTasksByAssignedToAction.php
src/Actions/Metrics/GetEstimatedHoursCompletedByEmployeesAction.php
src/Models/Board.php
src/Models/Column.php
src/Models/Row.php
src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/kanban/kanbanComponents/KanbanTaskModal.vue
src/resources/js/mixins/ajaxCallsMixin.js

[XGUARD-3736]
[XGUARD-3743]
[XGUARD-3755]
fixed these:
[XGUARD-3736]
[XGUARD-3743]
[XGUARD-3755]
[XGUARD-3736]: https://snapx-team.atlassian.net/browse/XGUARD-3736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3743]: https://snapx-team.atlassian.net/browse/XGUARD-3743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3755]: https://snapx-team.atlassian.net/browse/XGUARD-3755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3736]: https://snapx-team.atlassian.net/browse/XGUARD-3736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Fixing deleted issues

---

src/Actions/Metrics/GetAverageTimeToCompletionByBadgeAction.php
src/Actions/Metrics/GetAverageTimeToCompletionByEmployeeAction.php
src/Actions/Notifications/NotifyEmployeesAction.php
src/Actions/Notifications/NotifyOfTasksWithDeadlineInNext24Action.php
src/Actions/Rows/DeleteRowAction.php
src/Actions/Rows/UpdateRowIndexesAction.php
src/Enums/DateTimeFormats.php
src/Enums/LoggableTypes.php
src/Models/Column.php
src/Models/EmployeeBoardNotificationSetting.php
src/Models/Log.php
src/Models/Row.php
src/Models/Task.php
src/Models/TaskVersion.php
src/Notifications/TasksWithIncomingDeadline.php
src/Repositories/ColumnsRepository.php
src/Repositories/RowsRepository.php
tests/Unit/Actions/Rows/UpdateRowIndexesActionTest.php
vendor/composer/ClassLoader.php

fixing bugs [XGUARD-3743] and  [XGUARD-3860]
fixing metrics issue with valid date combinations sometimes throwing error
fixing issue where updating a task causes it to duplicate in other rows
[XGUARD-3743]: https://snapx-team.atlassian.net/browse/XGUARD-3743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[XGUARD-3860]: https://snapx-team.atlassian.net/browse/XGUARD-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

card duplication and metrics fix

---

src/Actions/Badges/CreateBadgeAction.php
src/Actions/ErpShareables/CreateErpShareablesAction.php
src/Actions/ErpShareables/UpdateErpShareablesDescriptionAction.php
src/Actions/Tasks/CreateTaskAction.php
src/Actions/Tasks/DeleteTaskFilesAction.php
src/Actions/Tasks/PlaceTaskAction.php
src/Actions/Tasks/RemoveTaskFromGroupAction.php
src/Actions/Tasks/StoreTaskFilesAction.php
src/Actions/Tasks/SyncAssignedEmployeesToTaskAction.php
src/Actions/Tasks/UpdateGroupAction.php
src/Actions/Tasks/UpdateTaskAction.php
src/Actions/Tasks/UpdateTaskCardIndexesAction.php
src/Actions/Tasks/UpdateTaskColumnAndRowAction.php
src/Actions/Tasks/UpdateTaskDescriptionAction.php
src/Actions/Tasks/UpdateTaskFilesAction.php
src/Actions/Tasks/UpdateTaskStatusAction.php
src/Http/Controllers/TaskController.php
src/Models/Employee.php
src/Models/SharedTaskData.php
src/Models/Task.php
src/Models/TaskFile.php
src/Repositories/TasksRepository.php
src/resources/js/components/global/Avatar.vue
src/resources/js/components/global/taskComponents/ViewTaskData.vue
src/resources/js/components/kanban/Kanban.vue
src/resources/js/components/kanban/kanbanComponents/AddTaskByColumnModal.vue
src/resources/js/components/kanban/kanbanComponents/KanbanBar.vue
src/resources/js/components/kanban/kanbanComponents/KanbanTaskModal.vue
src/resources/js/mixins/ajaxCallsMixin.js
tests/Unit/Actions/Tasks/UpdateTaskCardIndexesActionTest.php

added sort option
Constants refactor
Fixed a bug where creating a task without time estimate from column causes error

[XGUARD-4195][XGUARD-4238][XGUARD-4239]

---

src/resources/js/components/kanban/Kanban.vue
src/resources/js/components/kanban/kanbanComponents/KanbanBar.vue

saving selected sort method for each kanban in local storage

[XGUARD-4314] save kanban sort method

---

src/resources/js/components/kanban/kanbanComponents/TaskCard.vue

fix dragging when user selected

[XGUARD-4592] fix dragging when user selected

---

src/Models/Comment.php
src/Models/Log.php
src/resources/js/components/global/taskComponents/TaskComments.vue
src/resources/js/components/global/taskComponents/ViewTaskData.vue

Comments were broken if a user left a comment on a task and then was deleted as a kanban user.
Now If an employee is deleted, we can still see their comment and avatar and comments are no longer broken

[XGUARD-4673] fix broken comments

---

.circleci/config.yml
src/Http/Controllers/TaskController.php
src/Models/Employee.php
src/Repositories/EmployeesRepository.php
src/Repositories/LogsRepository.php
src/Repositories/TasksRepository.php
src/resources/js/components/dashboard/Dashboard.vue
src/resources/js/components/global/Badge.vue
src/resources/js/components/global/toastComponenents/CopyLinkToast.vue
src/resources/js/mixins/ajaxCallsMixin.js
src/routes/web.php
tests/Unit/Repositories/EmployeesRepositoryTest.php
tests/Unit/Repositories/TaskRepositoryTest.php

A toast message appears when you create a new task that when clicked will copy the backlog task url to clipboard. 

[XGUARD-5608] Copy backlog task link when creating task from dashboard

---

src/resources/js/App.vue
src/resources/js/components/backlog/Backlog.vue
src/resources/js/components/backlog/backlogComponents/TaskPane.vue
src/resources/js/components/global/taskComponents/RelatedTasks.vue
src/resources/js/components/global/taskComponents/ViewTaskData.vue

All frontend fix
related task links in the backlog will now open the clicked task in the task pane

[XGUARD-5605]  fix related tasks link in backlog page
